version: '2'
services:
  moodle:
    build: .
    ports:
     - "8080:80"
    volumes:
      - "./moodle_data:/var/moodle_data"
      - "./custom_config.php:/etc/moodle.d/50-custom.php"
    depends_on:
      - postgres
  postgres:
    image: postgres
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: moodle

volumes:
  pg_data:
